const data = [
  { From: ['PHNL'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KEOLA3.LIH', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or below 8,000', Route: 'KEOLA3.KEOLA.HNL258R..LIH148R.LIH', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK5.MKK', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PALAY3.LNY', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'N/A', Route: 'PALAY3.LNY.CAMPS4.OGG', Restrictions: 'Standard / Modified Flows' },
  { From: ['PHNL'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PALAY3.LNY.V2..V17.OGG', Restrictions: 'OGG ILS OTS' },
  { From: ['PHNL'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'MKK5.MKK.V22.OGG', Restrictions: 'South Flow' },
  { From: ['PHNL'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At or above 7,000', Route: 'MKK5.MKK.V22.OGG', Restrictions: 'Standard Flow' },
  { From: ['PHNL'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At 5,000', Route: 'MKK5.MKK.V8.BLUSH.V6.OGG', Restrictions: 'Standard / South Flow' },
  { From: ['PHNL'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK5.MKK.MKK100R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'At or above 13,000', Route: 'MKK5.PULPS.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'At or below 12,000', Route: 'PALAY3.LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'PALAY3.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PALAY3.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PALAY3.LNY.KAYAK6.KOA', Restrictions: 'KOA ILS OTS' },
  { From: ['PHNL'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PALAY3.LNY.V16.UPP.UPP174R.JASON..MUE', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHNM'], Typey: ['ALL'], Altitude: 'At or above 5,400', Route: 'MKK5.MKK.V8.BLUSH.VB6.OGG.V11.BARBY.HNM', Restrictions: 'At or below 8,300' },
  { From: ['PHNL'], To: ['PHNM'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'MKK5.MKK.V22.BARBY.HNM', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHUP'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK5.MKK..LUP', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHNL'], Typey: ['JETS'], Altitude: 'At or above 9,000', Route: 'MAUI5.OGG..LNY.JULLE5.HNL', Restrictions: 'Standard / Modified Flow' },
  { From: ['PHOG'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'BEACH4.LNY.JULLE5.HNL', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHNL'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'OGG.V6.BLUSH.V8.HNL', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHNL'], Typey: ['C208s'], Altitude: 'At or above 8,000', Route: 'OGG.V6.BLUSH.V8.MKK.MKK300R.BAMBO.V12.HNL', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHNL'], Typey: ['C208s'], Altitude: 'At or above 8,000', Route: 'OGG.V6.BLUSH.V8.MKK..BAMBO.V12.HNL', Restrictions: 'RNAV/GPS equipped' },
  { From: ['PHOG'], To: ['PHKO'], Typey: ['JETS'], Altitude: 'N/A', Route: 'ONOHI2.ONOHI.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'At or above 8,100', Route: 'BEACH4.HARPO.V5.KOA', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHKO'], Typey: ['PROPS'], Altitude: 'At or above 8,100', Route: 'BEACH4.HARPO.V2.MAKEN.V5.KOA', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHKO'], Typey: ['PROPS'], Altitude: 'At or below 8,100', Route: 'ONOHI2.BARBY.V11.UPP.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'At or below 8,100', Route: 'OGG.V1.HARPO.V2.MAKEN .V5.KOA', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'N/A', Route: 'ONOHI2.BARBY.V22.BONUS.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHTO'], Typey: ['ALL'], Altitude: 'At or above 10,000', Route: 'BEACH4.HARPO.V21.PUMIC.V15.ITO', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'At or above 10,000', Route: 'ONOHI2.BARBY.V11.PULPS.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'At or below 10,000', Route: 'ONOHI2.BARBY.V11.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'At or above 8,100', Route: 'BEACH4.HARPO.V2.ITO', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ONOHI2.BARBY.V11.UPP.UPP174R.JASON..MUE', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'BEACH4.HARPO.V2.UPP.UPP174R.JASON..MUE', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHLI'], Typey: ['JETS'], Altitude: 'At or above 9,000', Route: 'MAUI5.OGG..LNY.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHLI'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'OGG.V6.BLUSH.CKH075R.CKH.V12.KEOLA.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'BEACH4.LNY.V16.NAPUA..LIH', Restrictions: 'South Flow' },
  { From: ['PHOG'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'OGG.V6.BLUSH.V8.MKK.MKK100R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'OGG.V1.HARPO.V2.LNY', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'OGG.V6..V8.MKK', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHNM'], Typey: ['PROPS'], Altitude: 'At or above 7,000', Route: 'ONOHI2.BARBY..HNM', Restrictions: 'N/A' },
  { From: ['PHTO'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.LNY.JULLE5.HNL', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHNL'], Typey: ['JETS'], Altitude: 'N/A', Route: 'ITO.PARIS4.PARIS.V2.UPP.V16.LNY.JULLE5.HNL', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHNL'], Typey: ['PROPS'], Altitude: 'At or above 7,000', Route: 'ITO.PARIS4.PARIS.V2.UPP.V16.LNY.JULLE5.HNL', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or above 10,000', Route: 'ITO.V22.OKALA.V16.NAPUA..LIH', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or above 10,000', Route: 'PARIS4.PARIS.V2.UPP.V23.FIRES.V20.JULLE.V16.NAPUA..LIH', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or below 9,000', Route: 'ITO.V22.OKALA.V16.KEOLA.HNL258R..LIH148R.LIH', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or below 9,000', Route: 'PARIS4.PARIS.V2.LNY.V16.KEOLA.HNL258R..LIH148R.LIH', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'At or above 8,000', Route: 'ITO.V22.OKALA.V16.UPP.V2.HARPO.CAMPS4.OGG', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'PARIS4.PARIS.V2.HARPO.CAMPS4.OGG', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.LNY.LNY014R.BOGEE..JHM', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PARIS4.PARIS.V2.UPP.V16.LNY.LNY014R.BOGEE..JHM', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'At or above 9,000', Route: 'ITO.V22.OKALA.VECKI9.KOA', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'At 8,000', Route: 'ITO.V22.OKALA.V16.TIGAH.V3.MUE.VECKI9.KOA', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PARIS4.PARIS.V2.UPP.VECKI9.KOA', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.TIGAH.V3.MUE', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PARIS4.PARIS.V3.MUE', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHMM'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V8.HNL', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHNL'], Typey: ['C208'], Altitude: 'N/A', Route: 'HAPAI3.BAMBO.V12.HNL', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V7.LNY', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'N/A', Route: 'MKK.V7.LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'BLUSH2.BLUSH.V6.OGG', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.MKK100R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V7.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'N/A', Route: 'MKK.V7.LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'MKK.V7.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V8.ALANA.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.HNL', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.MKK', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.HNL.V2.LNY', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'N/A', Route: 'LIH.V15.HNL.V2.LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At or above 7,000', Route: 'LIH.V15.MKK.V22.OGG', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At or below 6,000', Route: 'LIH.V15.MKK.V8.BLUSH.V6.OGG', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.MKK.MKK100R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.HNL.V2.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.HNL.V2.LNY.V16.UPP.UPP174R.JASON..MUE', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'At or above 10,000', Route: 'LIH.V15.HNL.V2.LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'At or below 9,000', Route: 'LIH.V15.HNL.V2.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JHM..CHAIN.JULLE5.HNL', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY.V16.UPP.UPP174R.JASON..MUE', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY', Restrictions: 'N/A' },
  { From: ['PHJH'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JHM..CHAIN.LNY360R.LNY.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHNL'], Typey: ['PROPS'], Altitude: 'At or below 6,000', Route: 'LUP..MKK.V8.HNL', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHNL'], Typey: ['C208'], Altitude: 'At or above 7,000', Route: 'LUP..MKK.MKK300R.BAMBOO.V12.HNL', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHJH'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'LUP..MKK.MKK100R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHNY'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'LUP..MKK.V7.LNY', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'LUP..MKK.V8.BLUSH.V6.OGG', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'LUP..MKK.V7.LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHUP'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At or above 5,000', Route: 'LUP..MKK.V7.LNY.V2..V17..OGG', Restrictions: 'OGG ILS OTS' },
  { From: ['PHKO'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOA.V1.HARPO.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHOG'], Typey: ['C208'], Altitude: 'At or above 6,000', Route: 'KOA.KOA191R.CIGAK..MYNAH.V11.UPP.V2.HARPO.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'At or above 9,000', Route: 'KOA.KOA351R.ONOHI.V22.OGG', Restrictions: 'South Flow' },
  { From: ['PHKO'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'Below 9,000', Route: 'KOA.V5.MYNAH.V11.OGG', Restrictions: 'South Flow' },
  { From: ['PHKO'], To: ['PHTO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOA.V5.MYNAH.V3.PARIS.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOA.V5.MYNAH.V3.MUE', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'At or above 13,000', Route: 'KOA.V20.HOKLA.JULLE5.HNL', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'At or below 12,900', Route: 'KOA.V7.LNY.JULLE5.HNL', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or above 13,000', Route: 'KOA.V20.JULLE.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or below 12,900', Route: 'KOA.V7.LNY.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHJH'], Typey: ['C208'], Altitude: 'At or above 6,000', Route: 'KOA.KOA191R.CIGAK..MYNAH.V11.UPP.V2.LNY.LNY014R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHTO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.PARIS.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.MYNAH.V5.KOA', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'MUE.V3.TIGAH.V16.UPP.V2.HARPO.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.TIGAH.V16.LNY.LNY014R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.TIGAH.V16.LNY', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.TIGAH.V16.LNY.V7.MKK', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.TIGAH.V16.LNY.JULLE5.HNL', Restrictions: 'N/A' },
  { From: ['PHMU'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUE.V3.TIGAH.V16.UPP.V23.FIRES.V20.JULLE.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.JULLE5.HNL', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHNL'], Typey: ['C208'], Altitude: 'At or below 6,000', Route: 'LNY.V7.MKK.MKK300R.BAMBO.V12.HNL', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHJH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.LNY014R.BOGEE..JHM', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHMU'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.V16.UPP.UPP174R.JASON..MUE', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'N/A', Route: 'LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'At or above 5,000', Route: 'KEOLA3.KEOLA..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'At or below 5,000', Route: 'HNL..HHI', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'At or below 9,000', Route: 'HNL..MUGGE..NGF', Restrictions: 'N/A' },
  { From: ['PHNL'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'At or below 3,000', Route: 'HNL..JRF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'At or above 9,000', Route: 'MAUI5.LNY.V16.SOK..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHHI'], Typey: ['JETS'], Altitude: 'At or above 9,000', Route: 'MAUI5.OGG..LNY.V16.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHHI'], Typey: ['PROPS'], Altitude: 'At or below 8,000', Route: 'OGG.V6.BLUSH.V8.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PNGF'], Typey: ['JETS'], Altitude: 'At or above 9,000', Route: 'MAUI5.OGG.V22.MKK..NUDSE..NGF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PNGF'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'OGG.V6.BLUSH..NUDSE..NGF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'At or below 6,900', Route: 'OGG.V6.BLUSH.V8.MKK..NUDSE..NGF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHJR'], Typey: ['PROPS'], Altitude: 'At or below 8,000', Route: 'OGG.V1.HARPO.V2.LNY.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHJR'], Typey: ['C208'], Altitude: 'N/A', Route: 'OGG.V6.PLUMB.V22.MKK.MKK300R.BAMBO.V12.HNL..SIMSN..JRF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHJR'], Typey: ['PROPS'], Altitude: 'At or above 8,100', Route: 'OGG..RV LNY.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHOG'], To: ['PHJR'], Typey: ['JETS'], Altitude: 'At or above 9,000', Route: 'MAUI5.OGG..LNY.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHTO'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.SOK..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PHTO'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.ALANA..HHI', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'PARIS4.PARIS.V2.UPP.V16.ALANA..HHI', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'ITO.V22.OKALA.V16.LNY.V7.MKK..NUDSE..NGF', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'At or above 7,000', Route: 'PARIS4.PARIS.V2.UPP.V16.LNY.V7.MKK..NUDSE..NGF', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHJR'], Typey: ['JETS'], Altitude: 'N/A', Route: 'ITO.V22.OKALA.V16.ALANA..GECKO..JRF', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHJR'], Typey: ['JETS'], Altitude: 'N/A', Route: 'PARIS4.PARIS.V2.UPP.V16.ALANA..GECKO..JRF', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHTO'], To: ['PHJR'], Typey: ['PROPS'], Altitude: 'At or above 8,000', Route: 'ITO.V22.OKALA.V16.GECKO..JRF', Restrictions: 'ITO ATCT Open' },
  { From: ['PHTO'], To: ['PHJR'], Typey: ['PROPS'], Altitude: 'At or above 7,000', Route: 'PARIS4.PARIS.V2.UPP.V16.GECKO..JRF', Restrictions: 'ITO ATCT Closed' },
  { From: ['PHKO'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'Below 13,000', Route: 'KOA.V7.LNY.V16.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'At or above 13,000', Route: 'KOA.V20.JULLE.V16.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOA.V7.MKK..NUDSE..NGF', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'Below 13,000', Route: 'KOA.V7.LNY.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHKO'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'At or above 13,000', Route: 'KOA.V20.JULLE.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.V16.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHNY'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LNY.V16.ALANA..GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V8.ALANA..HHI', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MKK.V8.GECKO..JRF', Restrictions: 'N/A' },
  { From: ['PHMM'], To: ['PHJR'], Typey: ['C208'], Altitude: 'N/A', Route: 'HAPAI3.BAMBO.V12.HNL..SIMSN..JRF', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH..KREEN..SOK..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHHI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.HNL..HHI', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH..KOMAZ..FUZZE..NIKKI..NGF', Restrictions: 'N/A' },
  { From: ['PHLI'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'N/A', Route: 'LIH.V15.BOOKE..KEOLA..TARLE..JRF', Restrictions: 'N/A' },
  { From: ['PBKH'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'SOK7.SOK.V15.HNL', Restrictions: 'N/A' },
  { From: ['PBKH'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'N/A', Route: 'SOK7.SOK.V15.MKK.V22.OGG', Restrictions: 'N/A' },
  { From: ['PBKH'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'SOK7.SOK.V16.MORKE..LIH', Restrictions: 'N/A' },
  { From: ['PBKH'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'N/A', Route: 'SOK7.SOK.V15.BOOKE..KEOLA..TARLE..JRF', Restrictions: 'N/A' },
  { From: ['PBKH'], To: ['PNGF'], Typey: ['ALL'], Altitude: 'N/A', Route: 'SOK7.SOK..KOMAZ..FUZZE..NIKKI..NGF', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'N/A', Route: 'KOKOH2.LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'KOKOH2.MKK.V8.BLUSH.V6.OGG', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHTO'], Typey: ['JETS'], Altitude: 'At or above 13,000', Route: 'KOKOH2.MKK..PULPS.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHTO'], Typey: ['PROPS'], Altitude: 'N/A', Route: 'KOKOH2.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHKO'], Typey: ['JETS'], Altitude: 'Below 14,400', Route: 'KOKOH2.MKK.V7.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHKO'], Typey: ['JETS'], Altitude: 'Above 14,500', Route: 'KOKOH2.MKK.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHNY'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOKOH2.LNY', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'KOKOH2.MKK', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'At or below 9,000', Route: 'GECKO2.GECKO.V16.KEOLA.HNL258R..LIH148R..LIH', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'GECKO2.GECKO.V16.NAPUA..LIH', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'At or above 10,000', Route: 'GECKO2.GECKO.V16.SOK..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PHHI'], To: ['PNGF'], Typey: ['ALL'], Altitude: '5,000 – 9,000', Route: 'KOKOH2.CKH..MASAE..NUDSE..NGF', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHNL'], Typey: ['ALL'], Altitude: 'N/A', Route: 'MUGGE1.HNL', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHOG'], Typey: ['ALL'], Altitude: 'N/A', Route: 'HELUX5.MKK.V22.OGG', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHTO'], Typey: ['ALL'], Altitude: 'At or above 10,000', Route: 'HELUX5.MKK.V7.LNY.V21.PUMIC.V15.ITO', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHTO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'HELUX5.MKK.V7.LNY.V16.UPP.V2.ITO', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'Below 14,400', Route: 'HELUX5.MKK.V7.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'Above 14,500', Route: 'HELUX5.MKK.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHMM'], Typey: ['ALL'], Altitude: 'N/A', Route: 'HELUX5.MKK', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHLI'], Typey: ['ALL'], Altitude: 'N/A', Route: 'NGF5.SOK..LIH', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PBKH'], Typey: ['ALL'], Altitude: 'N/A', Route: 'NGF5.SOK..ASAYA..BKH', Restrictions: 'N/A' },
  { From: ['PNGF'], To: ['PHJR'], Typey: ['ALL'], Altitude: 'At or below 16,000', Route: 'MUGGE1.HNL..GECKO..TARLE..JRF', Restrictions: 'N/A' },
  { From: ['PHJR'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'N/A', Route: 'JRF..LNY.CAMPS4.OGG', Restrictions: 'N/A' },
  { From: ['PHJR'], To: ['PHOG'], Typey: ['JETS'], Altitude: 'At or above 7,000', Route: 'JRF..MKK.V22.OGG', Restrictions: 'Maui South Flow' },
  { From: ['PHJR'], To: ['PHOG'], Typey: ['PROPS'], Altitude: 'At or below 6,000', Route: 'JRF..MKK.V8.BLUSH.V6.OGG', Restrictions: 'Maui South Flow' },
  { From: ['PHJR'], To: ['PHOG'], Typey: ['C208'], Altitude: 'N/A', Route: 'JRF..IWOHI..CKH.V15.MKK.V22.PLUMB.V6.OGG', Restrictions: 'N/A' },
  { From: ['PHJR'], To: ['PHKO'], Typey: ['ALL'], Altitude: 'N/A', Route: 'JRF..PALAY.V2.LNY.VECKI9.KOA', Restrictions: 'N/A' },
  { From: ['PHJR'], To: ['PHMM'], Typey: ['C208'], Altitude: 'N/A', Route: 'JRF..IWOHI..CKH.V15.MKK', Restrictions: 'N/A' }
];

function search() {
  
    const selectedFrom = document.getElementById('selectedFrom').value.toLowerCase();
    const selectedTo = document.getElementById('selectedTo').value.toLowerCase();

    const filteredData = data.filter(route =>
        String(route.From).toLowerCase().includes(selectedFrom) &&
        String(route.To).toLowerCase().includes(selectedTo)
      );
    const searchResultsContainer = document.getElementById('searchResults');
    searchResultsContainer.innerHTML = '';
  
    if (filteredData.length === 0) {
      const noResultMessage = document.createElement('h1');
      noResultMessage.textContent = 'No result!';
      searchResultsContainer.appendChild(noResultMessage);
    } else {
      filteredData.forEach(route => {
        const routeElement = document.createElement('div');
        routeElement.innerHTML = `<b>From:<b> ${route.From} <b>To:<b> ${route.To}<br><b>Type:<b> ${route.Typey}<br><b>Route:<b> ${route.Route}<br><b>Altitude:<b> ${route.Altitude}<br><b>Restrictions:<b> ${route.Restrictions}`;
        searchResultsContainer.appendChild(routeElement);
      });
    }
  }
  
  
